<script type="text/javascript">
    $(document).ready(function(){
       
        $("#frmUsuario").validate({
            // Define as regras
            rules:{
                vhr_nome:{
                    // campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
                    required: true, 
                    minlength: 5
                },
                vhr_login:{
                    // campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
                    required: true, 
                    minlength: 14
                    //verificaCPF: true
                },
                vhr_email:{
                    // campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
                    required: true,
                    email : true
                },
                id_perfil:{
                    // campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
                    required: true 
                },
                id_setorial:{
                    required: true
                    /*minlength: 6*/
                }

            },
            // Define as mensagens de erro para cada regra
            messages:{
                vhr_nome:{
                    required: "<br />O campo Nome é obrigatório",
                    minlength: "<br />O nome deve conter no mínimo 5 caracteres"
                },
                vhr_login:{
                    required: "<br />O campo CPF é obrigatório",
                    minlength: "<br />O CPF deve conter no mínimo 11 caracteres"
                    //verificaCPF: "<br />CPF inv&aacute;lido"
                },
                vhr_email:{
                    required: "<br />O campo Email é obrigatório",
                    email: "<br />Email inv&aacute;lido"
                },
                id_perfil:{
                    required: "<br />O campo Perfil é obrigatório"
                },
                id_setorial:{
                    required: "<br />O campo Setorial é obrigatório"
                }
            },
            
            submitHandler: function(form){
                $("#msgError").html('');

                var n = $("input.checkboxSetorial:checked").length;
                
                if(n <= 0){
                    $("#msgError").html("<font class='red'><b>Selecione no mínimo uma setorial para o usuário.</b></font>");
                    return false;
                }
                
                <?php if($this->dadosUsuario['id_perfil'] == 1 && $this->dadosUsuario['vhr_login'] != "00000000000"): ?>
                if(n > 1){
                    $("#msgError").html("<font class='red'><b>Inscritos só podem fazer parte de uma Setorial.</b></font>");
                    return false;
                }
                <?php endif; ?>
                
                form.submit();
            }
                            
        });

        $("#vhr_login").mask('999.999.999-99');
        
        $("#cancelar").click(function(){
            redirecionar('<?php echo $this->url(array('controller' => 'usuario', 'action' => 'index')); ?>');
        });
        
        <?php if($this->dadosUsuario['id_perfil'] == 1): ?>
            var n = $("input.checkboxSetorial:checked").length;
            if(n >= 1){
                /*$("input.checkboxSetorial").each(function(){
                    if(!$(this).is(':checked')){
                        $(this).attr("disabled",true);
                    }
                });*/
            }
        <?php endif; ?>
        
    }); //fecha $('document').ready
</script>

<form name="frmUsuario" id="frmUsuario" class="formulario" action="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'alterar')); ?>"  method="POST">
    <fieldset>
        <legend>Editar Usuário</legend>
        <table class="w800" cellpading="0" cellspacing="0">
            <tr>
                <td style="width: 120px">Nome Completo: *</td>
                <td><input type="text" name="vhr_nome" id="vhr_nome" class="input_simples" value="<?php echo $this->dadosUsuario['vhr_nome']; ?>"></td>
            </tr>
            <tr>
                <td>CPF: *</td>
                <td><input type="text" readonly="readonly" name="vhr_login" id="vhr_login" class="input_simples" maxlength="14" value="<?php echo $this->dadosUsuario['vhr_login']; ?>"></td>
            </tr>
            <tr>
                <td>Email: *</td>
                <td><input type="text" name="vhr_email" id="vhr_email" class="input_simples" value="<?php echo $this->dadosUsuario['vhr_email']; ?>"></td>
            </tr>
            <?php if($this->dadosUsuario['id_perfil'] > 1){ ?>
            <tr>
                <td>Perfil: *</td>
                <td>
                    <select name="id_perfil" id="id_perfil" class="input_simples">
						<option value="1" <?php if($this->dadosUsuario['id_perfil'] == 1){ echo 'selected=selected'; } ?>>Inscrito</option>
                        <?php if($this->usuario->id_perfil == 4): //usuario administrado?>
                        <option value="4" <?php if($this->dadosUsuario['id_perfil'] == 4){ echo 'selected=selected'; } ?>>Administrador</option>
                        <?php endif; ?>
                        <option value="2" <?php if($this->dadosUsuario['id_perfil'] == 2){ echo 'selected=selected'; } ?>>Componente da comissão</option>
                        <option value="3" <?php if($this->dadosUsuario['id_perfil'] == 3){ echo 'selected=selected'; } ?>>Presidente da comissão</option>
						<?php if($this->usuario->id_perfil == 4): //usuario administrado?>
						<option value="5" <?php if($this->dadosUsuario['id_perfil'] == 5){ echo 'selected=selected'; } ?>>Comissão da Nacional</option>
						<?php endif; ?>
                        
                    </select>
                </td>
            </tr>
            <?php } ?>
            <tr>
                <td>Nova Senha:</td>
                <td><input type="password" name="vhr_senha" id="vhr_senha" class="input_simples" value=""></td>
            </tr>
            <tr id="trSetorial">
                <td>Setoriais: *</td>
                <td>
                    <?php
                    $ids = array();
                    if(isset($this->setoriaisUsuario) && count($this->setoriaisUsuario)>0){
                        $ids = $this->setoriaisUsuario;
                    }
                    foreach ($this->setoriaisCombo as $setoriaisCombo) { ?>
                    <input type="checkbox" name="id_setorial[]" value="<?php echo $setoriaisCombo['id_setorial']; ?>" class="input_simples checkboxSetorial" <?php if(in_array($setoriaisCombo['id_setorial'], $ids)){ echo 'checked="checked"'; } ?>> <?php echo $setoriaisCombo['vhr_nome']; ?><br/>
                    <?php } ?>
                    <span id="msgError"></span>
                </td>
            </tr>
        </table>
    </fieldset>
    <table class="w800" cellpading="0" cellspacing="0" id="tblBotoes">
        <tr>
            <td class="centro">
                <input type="submit" name="btn_salvar" id="btn_salvar" value="Salvar" class="btn">&nbsp;&nbsp;
                <input type="button" name="cancelar" id="cancelar" value="Cancelar" class="btn">&nbsp;&nbsp;<br />
<!--                <br/><span class="red">*Atenção:</span> Você poderá salvar os dados da sua inscrição a qualquer momento durante o preenchimento mas isso não implica
                que a mesma foi concluída ou enviada. Após concluir o cadastro de toda a sua inscrição você deverá clicar em "Enviar inscrição".
                Seu cadastro só será considerado após você realizar a operação de enviar a inscrição.-->
            </td>
        </tr>
    </table>
</form>
