<script>
    $(document).ready(function(){
        
        
    }); //fecha $('document').ready
    
</script>
<br>
    <table class="w900" cellpading="0" cellspacing="0" style="background-color: #fff; height: 400px;">
        <?php //if($this->usuario->id_perfil > 1): ?>
        <tr class="" style="background-color: #fff">
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'emails', 'action' => 'form-enviar-email-inabilitados')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-email.png"><br>
                    <span style="font-size: 12pt; font-weight: bold;">Enviar e-mail para Inscritos NÃO VALIDADOS</span>
                </a>
            </td>
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'emails', 'action' => 'form-enviar-email-habilitados')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-email.png"><br>
                    <span style="font-size: 12pt; font-weight: bold;">Enviar e-mail para Inscritos VALIDADOS</span>
                </a>
            </td>
        </tr>
        <?php //endif; ?>
    </table>
