<?php header("Content-Type: text/html; charset=ISO-8859-1"); ?>
<script type="text/javascript">
    $(document).ready(function(){
        
        $("#sltSetoriais").change(function(){
            var idSetorial = $(this).val();
                $("#resultadoTotais").html("");
                $('#resultadoTotais').html('<br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'relatorios', 'action' => 'listar-uf-acompanhamento-votacao')); ?>',
                    data :
                        {
                        idSetorial : idSetorial
                    },
                    success: function(data){
                        $('#resultadoTotais').html(data);
                    },
                    type : 'post'
                });
        });
     }); //fecha document.read
    
</script>

<div id="setoriaisUsuario" style="display: none;"></div>

<div id="resultadoPesquisa">
    <fieldset>
        <legend>Acompanhamento da Eleição de Delegados (Votação)</legend>
        <table class="w900">
            <tr>
                <td>
                    <strong>Setoriais:</strong>
                    <select class="input_simples" id="sltSetoriais" name="sltSetoriais">
                        <option value="" selected> -  Selecione -</option>
                        <?php foreach ($this->setoriais as $setorial) { ?>
                            <option value="<?php echo $setorial->id_setorial; ?>"><?php echo $setorial->vhr_nome; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
        </table>
        <div id="resultadoTotais"><br /><center><strong>Informe um Setorial</strong></center><br /></div>
    </fieldset>
</div>
