<?php header("Content-Type: text/html; charset=ISO-8859-1"); ?>
<script>
    $(document).ready(function(){


     }); //fecha document.read

</script>

<table style="width: 100%; border: 0px #ccc solid;" cellpadding="0" cellspacing="1" >
    <tr class="bg_title_grid">
        <td width="20%">Nome</td>
        <td width="10%">Tipo Inscrição</td>
        <td width="10%">Avaliação</td>
    </tr>
    <?php if(count($this->registros)>0):?>
        <?php $ct=1; foreach ($this->registros as $registro): $bg =($ct%2)? "bg_linha_grid3": "bg_linha_grid3"; ?>
        <tr class="<?php echo $bg;?>">
            <td width="40%"><b><?php echo strtoupper($registro->nome);?></b></td>
            <td width="30%"><?php echo ($registro->tipocadastro == 1) ? 'Eleitor' : 'Candidato';?></td>
            <td width="30%"><?php echo ($registro->bol_validacaofinal == 1) ? '<font color="green"><b>Validado</b></font>' : '<font color="red"><b>Não Validado</b></font>';?></td>
        </tr>
        <?php $ct++; endforeach;?>
    <?php else:?>
        <tr>
            <td width="100%" colspan="3" class="centro"><i>Não foram encontradas informações para esta UF.</i></td>
        </tr>
    <?php endif;?>
</table>
<br>