<?php header("Content-Type: text/html; charset=ISO-8859-1"); ?>
<script type="text/javascript">
    $(document).ready(function(){
        
        $("#cpf").mask('999.999.999-99');
        
        $('#btn_pesquisar').click(function(){
            
            var nome = $('#nome').val(),
                cpf = $('#cpf').val(),
                setorial = $('#setorial').val(),
                tipoInscricao = $('#tipoInscricao').val(),
                uf = $('#uf').val(),
                avaliacaoPresidente = $('#avaliacaoPresidente').val();
                
                $("#resultado-pesquisa").html("");
                $('#resultado-pesquisa').html('<br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'avaliacao', 'action' => 'listar-inscritos-avaliacao-final')); ?>',
                    data :
                        {
                        nome : nome,
                        cpf: cpf,
                        setorial : setorial,
                        tipoInscricao : tipoInscricao,
                        uf : uf,
                        avaliacaoPresidente : avaliacaoPresidente
                        //idSetoriais : '<//?php echo $this->arrIdSetoriais; ?>'
                    },
                    success: function(data){
                        $('#resultado-pesquisa').html(data);
                    },
                    type : 'post'

                });
        });
        
        $('#btn_limpar').click(function(){
            $("#resultado-pesquisa").html("");
            $('#resultado-pesquisa').html('<br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
            $.ajax({
                url : '<?php echo $this->url(array('controller' => 'avaliacao', 'action' => 'listar-inscritos-avaliacao-final')); ?>',
                data :
                {
                },
                success: function(data){
                    $('#resultado-pesquisa').html(data);
                },
                type : 'post'
            });
        });
        
        $("#resultado-pesquisa").html("");
        $('#resultado-pesquisa').html('<br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
        $.ajax({
            url : '<?php echo $this->url(array('controller' => 'avaliacao', 'action' => 'listar-inscritos-avaliacao-final')); ?>',
            data :
            {
            },
            success: function(data){
                $('#resultado-pesquisa').html(data);
            },
            type : 'post'
        });
     }); //fecha document.read
    
</script>

<div id="setoriaisUsuario" style="display: none;"></div>

<form name="frmPesquisa" id="frmPesquisa" class="formulario" action="<?php echo $this->url(array('controller' => 'avaliacao', 'action' => 'listar-inscritos-avaliacao-final')); ?>"  method="POST">
    <fieldset style="width: 1000px;">
        <legend>Filtro de Pesquisa</legend>
        <table  style="width: 1000px;" cellpading="0" cellspacing="0">
            <tr>
                <td style="width: 30px">Nome:</td>
                <td><input type="text" name="nome" id="nome" class="input_simples" value=""></td>
                <td style="width: 30px">Tipo de Inscrição:</td>
                <td>
                    <select name="tipoInscricao" id="tipoInscricao" class="input_simples">
                        <option value="0">- Selecione -</option>
                        <option value="1">Eleitor</option>
                        <option value="2">Candidato</option>
                    </select>
                </td>
                <td>Setorial:</td>
                <td>
                    <select name="setorial" id="setorial" class="input_simples">
                        <option value="0">- Selecione -</option>
                        <?php foreach ($this->setoriais as $setoriaisCombo) { ?>
                        <option value="<?php echo $setoriaisCombo['id_setorial']; ?>"><?php echo $setoriaisCombo['vhr_nome']; ?></option>
                    <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="6" align="center">
                    <input type="button" name="btn_pesquisar" id="btn_pesquisar" value="Pesquisar" class="btn">
                    <input type="reset" name="btn_limpar" id="btn_limpar" value="Limpar" class="btn">
                </td>
            </tr>
        </table>
    </fieldset>
</form>

<div id="resultado-pesquisa"  style="width: 1000px;"></div>
