<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
  <h1></h1><br />
  <h2><?php //echo $this->message ?></h2><br/>

  <?php if (isset($this->exception)): ?>
  
  <h2>Erro:</h2>
  <p>
      <?php echo $this->exception->getMessage() ?>
  </p>

  <h2>Trace:</h2>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>
  <br />
  <h2>Parametros da requisição:</h2>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>

</body>
</html>