<script>
    $(document).ready(function(){
        
        
    }); //fecha $('document').ready
    
</script>
<br>
    <table cellpading="0" cellspacing="0" style="width: 1000px; background-color: #fff; height: 400px;">
        <tr>
            <td colspan="8" class="centro">
                <br>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/logo-cnpc.gif"><br><br>
            </td>
        </tr>
        <?php if($this->usuario->id_perfil > 1): ?>
        <tr class="destacar">
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'recurso', 'action' => 'avaliacao-recurso-fase-um')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-recurso.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Avaliar Recurso<br><font size="2px">(1&ordf; Instância)</font></span>
                </a>
            </td>
			<?php if($this->usuario->id_perfil == 4 || $this->usuario->id_perfil == 5):?>
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'recurso', 'action' => 'avaliacao-recurso-fase-dois')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-recurso-2.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Avaliar Recurso<br><font size="2px">(2&ordf; Instância)</font></span>
                </a>
            </td>
			<?php endif; ?>
            <!--<td class="centro">
                <a href="<?php //echo $this->url(array('controller' => 'recurso', 'action' => 'avaliacao-recurso-fase-um')); ?>">
                    <img src="<?php //echo $this->baseUrl(); ?>/public/img/icn-recurso.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Avaliar Recurso<br>(Fase 2)</span>
                </a>
            </td>-->
            <td class="centro">
            <?php if($this->usuario->id_perfil == 2 || $this->usuario->id_perfil == 3 || $this->usuario->id_perfil == 4):?>
                <!--<a href="<//?php echo $this->url(array('controller' => 'avaliacao', 'action' => 'index')); ?>">
                    <img src="<//?php echo $this->baseUrl(); ?>/public/img/icn-avaliar-cadastro.png"><br>
                    <span style="font-size: 12pt; font-weight: bold;">Avaliar Cadastro</span>
                </a>-->
					<a href="<?php echo $this->url(array('controller' => 'avaliacao', 'action' => 'index')); ?>">
						<img src="<?php echo $this->baseUrl(); ?>/public/img/icn-avaliar-cadastro.png"><br>
						<span style="font-size: 12pt; font-weight: bold;">Avaliar Cadastro</span>
					</a>
            <?php else: ?>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-avaliar-cadastro-off.png"><br>
                <span style="font-size: 12pt; font-weight: bold;">Avaliar Cadastro</span>
            <?php endif; ?>
            </td>
            <td class="centro">
            <?php if($this->usuario->id_perfil == 4):?>
                <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'index')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-cadastrar-usuario.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Manter Usuários</span>
                </a>
            <?php else: ?>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-cadastrar-usuario-off.png"><br>
                <span style="font-size: 12pt; font-weight: bold; ">Manter Usuários</span>
            <?php endif; ?>
            </td>
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'relatorios', 'action' => 'index')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-relatorios.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Relatórios</span>
                </a>
            </td>
            <?php if($this->usuario->id_perfil == 4):?>
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'emails', 'action' => 'index')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-email.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Envio de E-mails</span>
                </a>
            </td>
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'habilitarsetorialuf', 'action' => 'habilitar-setorial-uf')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/ic-hablitar-setorial-uf.png" style="width: 100px;"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Habilitar Setorial/UF</span>
                </a>
            </td>
            <?php endif; ?>
        </tr>
        <?php else: ?>
        <tr class="destacar">
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'relatorios', 'action' => 'index')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-relatorios.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Relatórios</span>
                </a>
            </td>
            <td class="centro">
                <a href="<?php echo $this->url(array('controller' => 'recurso', 'action' => 'index')); ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/icn-relatorios.png"><br>
                    <span style="font-size: 12pt; font-weight: bold; ">Solicitar recurso</span>
                </a>
            </td>
        </tr>
        <?php endif; ?>
    </table>
